# Generated by Django 6.0.4 on 2026-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
    ]
