from django.urls import path

from .views import (
    panel_answer_create,
    panel_answer_delete,
    panel_answer_edit,
    panel_answer_list,
    panel_category_create,
    panel_category_delete,
    panel_category_edit,
    panel_category_list,
    panel_category_toggle,
    panel_certificate_delete,
    panel_certificate_list,
    panel_course_create,
    panel_course_delete,
    panel_course_edit,
    panel_course_featured_toggle,
    panel_course_list,
    panel_course_publish_toggle,
    panel_dashboard,
    panel_payment_list,
    panel_question_create,
    panel_question_delete,
    panel_question_edit,
    panel_question_list,
    panel_quiz_create,
    panel_quiz_delete,
    panel_quiz_edit,
    panel_quiz_list,
    panel_quiz_result_list,
    panel_lesson_create,
    panel_lesson_delete,
    panel_lesson_edit,
    panel_lesson_list,
    panel_review_delete,
    panel_review_list,
    panel_review_toggle,
    panel_section_create,
    panel_section_delete,
    panel_section_edit,
    panel_section_list,
    panel_site_settings,
    panel_user_create,
    panel_user_delete,
    panel_user_edit,
    panel_user_list,
    panel_user_toggle_block,
)

app_name = "panel"

urlpatterns = [
    path("", panel_dashboard, name="dashboard"),
    path("users/create/", panel_user_create, name="user_create"),
    path("users/", panel_user_list, name="user_list"),
    path("users/<int:pk>/edit/", panel_user_edit, name="user_edit"),
    path("users/<int:pk>/delete/", panel_user_delete, name="user_delete"),
    path("users/<int:pk>/block-toggle/", panel_user_toggle_block, name="user_toggle_block"),
    path("courses/", panel_course_list, name="course_list"),
    path("courses/create/", panel_course_create, name="course_create"),
    path("courses/<int:pk>/edit/", panel_course_edit, name="course_edit"),
    path("courses/<int:pk>/delete/", panel_course_delete, name="course_delete"),
    path("courses/<int:pk>/publish-toggle/", panel_course_publish_toggle, name="course_publish_toggle"),
    path("courses/<int:pk>/featured-toggle/", panel_course_featured_toggle, name="course_featured_toggle"),
    path("categories/", panel_category_list, name="category_list"),
    path("categories/create/", panel_category_create, name="category_create"),
    path("categories/<int:pk>/edit/", panel_category_edit, name="category_edit"),
    path("categories/<int:pk>/delete/", panel_category_delete, name="category_delete"),
    path("categories/<int:pk>/toggle/", panel_category_toggle, name="category_toggle"),
    path("sections/", panel_section_list, name="section_list"),
    path("sections/create/", panel_section_create, name="section_create"),
    path("sections/<int:pk>/edit/", panel_section_edit, name="section_edit"),
    path("sections/<int:pk>/delete/", panel_section_delete, name="section_delete"),
    path("lessons/", panel_lesson_list, name="lesson_list"),
    path("lessons/create/", panel_lesson_create, name="lesson_create"),
    path("lessons/<int:pk>/edit/", panel_lesson_edit, name="lesson_edit"),
    path("lessons/<int:pk>/delete/", panel_lesson_delete, name="lesson_delete"),
    path("quizzes/", panel_quiz_list, name="quiz_list"),
    path("quizzes/create/", panel_quiz_create, name="quiz_create"),
    path("quizzes/<int:pk>/edit/", panel_quiz_edit, name="quiz_edit"),
    path("quizzes/<int:pk>/delete/", panel_quiz_delete, name="quiz_delete"),
    path("questions/", panel_question_list, name="question_list"),
    path("questions/create/", panel_question_create, name="question_create"),
    path("questions/<int:pk>/edit/", panel_question_edit, name="question_edit"),
    path("questions/<int:pk>/delete/", panel_question_delete, name="question_delete"),
    path("answers/", panel_answer_list, name="answer_list"),
    path("answers/create/", panel_answer_create, name="answer_create"),
    path("answers/<int:pk>/edit/", panel_answer_edit, name="answer_edit"),
    path("answers/<int:pk>/delete/", panel_answer_delete, name="answer_delete"),
    path("quiz-results/", panel_quiz_result_list, name="quiz_result_list"),
    path("certificates/", panel_certificate_list, name="certificate_list"),
    path("certificates/<int:pk>/delete/", panel_certificate_delete, name="certificate_delete"),
    path("reviews/", panel_review_list, name="review_list"),
    path("reviews/<int:pk>/toggle/", panel_review_toggle, name="review_toggle"),
    path("reviews/<int:pk>/delete/", panel_review_delete, name="review_delete"),
    path("payments/", panel_payment_list, name="payment_list"),
    path("settings/", panel_site_settings, name="site_settings"),
]
