# Generated by Django 6.0.4 on 2026-05-30 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_instructors(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    TeacherProfile = apps.get_model("accounts", "TeacherProfile")
    for user in User.objects.filter(role="instructor"):
        TeacherProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=180)),
                ('experience', models.CharField(blank=True, max_length=180)),
                ('social_links', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'user__email'],
            },
        ),
        migrations.RunPython(create_profiles_for_existing_instructors, migrations.RunPython.noop),
    ]
