# Generated by Django 6.0.4 on 2026-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_course_certificate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_uz',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
