# Generated by Django 6.0.4 on 2026-05-29 14:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_lesson_course(apps, schema_editor):
    Lesson = apps.get_model("courses", "Lesson")
    for lesson in Lesson.objects.select_related("section", "section__course").all():
        if lesson.section_id and lesson.course_id != lesson.section.course_id:
            lesson.course_id = lesson.section.course_id
            lesson.save(update_fields=["course"])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_index', 'section__order_index', 'id']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.RunPython(backfill_lesson_course, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section'),
        ),
    ]
