# Generated by Django 6.0.4 on 2026-05-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_options_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='prompt_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='prompt_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='prompt_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_ru',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_uz',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='section',
            name='title_ru',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='section',
            name='title_uz',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
