# Generated by Django 6.0.4 on 2026-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SkillHub', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('primary_color', models.CharField(default='#11324d', max_length=20)),
                ('accent_color', models.CharField(default='#d97706', max_length=20)),
                ('footer_text', models.CharField(default='SkillHub helps ambitious learners turn momentum into mastery.', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_host', models.CharField(blank=True, max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=120)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
